**배열[행위치][열시작위치:열끝위치]**

: 특정 행을 선택한 후 열을 슬라이싱

In [3]:
import numpy as np

In [4]:
arr3 = np.arange(10,100,10).reshape(3,3)
arr3

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [6]:
# 1행의 0열과 1열 요소 선택
# arr3[1:2]
arr3[1][:2]

array([40, 50])

In [8]:
# 참고. 인덱싱 예
arr3[2][1]

80

**슬라이싱 된 배열에 값을 지정**

In [9]:
# 0~1행, 1~2열의 요소 변경
arr3[:2, 1:3]=np.array([[1,3],[4,1]])
arr3

array([[10,  1,  3],
       [40,  4,  1],
       [70, 80, 90]])