# NumPy 연산과 인덱싱
 - 배열 연산
 - 통계,수학, 행렬 연산
 - 인덱싱과 슬라이싱

**numpy 모듈 선언**

In [1]:
import numpy as np

# Array 연산

## 기본 연산(합, 차, 곱, 나눗셈 등) 

: 기본적으로 동일한 크기의 array 간 연산 수행

In [2]:
arr1 = np.array([[1,3,4], [4,3,6]])
arr1

array([[1, 3, 4],
       [4, 3, 6]])

In [3]:
arr2 = np.array([[10,11,12],[13,14,15]])
arr2

array([[10, 11, 12],
       [13, 14, 15]])

**배열의 합**

In [4]:
arr1 + arr2

array([[11, 14, 16],
       [17, 17, 21]])

**배열의 차**

In [5]:
arr1 - arr2

array([[ -9,  -8,  -8],
       [ -9, -11,  -9]])

**배열의 곱**

In [6]:
arr1 * arr2

array([[10, 33, 48],
       [52, 42, 90]])

**배열의 나눗셈**

In [7]:
arr1 / arr2

array([[0.1       , 0.27272727, 0.33333333],
       [0.30769231, 0.21428571, 0.4       ]])

**배열의 스칼라 곱**

In [10]:
arr2 * 2

array([[20, 22, 24],
       [26, 28, 30]])

**배열의 비교 연산**

In [11]:
arr2 > 20

array([[False, False, False],
       [False, False, False]])

## 배열의 Broadcasting 
- 서로 크기가 다른 array들의 연산이 가능하도록 배열을 자동적으로 변환하여 연산 수행

In [12]:
arr1

array([[1, 3, 4],
       [4, 3, 6]])

In [14]:
arr3 = np.array([10,11,12])
arr3

array([10, 11, 12])

In [15]:
arr1 + arr3

array([[11, 14, 16],
       [14, 14, 18]])

In [16]:
arr1 * 10

array([[10, 30, 40],
       [40, 30, 60]])

In [17]:
arr1 ** 2

array([[ 1,  9, 16],
       [16,  9, 36]], dtype=int32)

**브로드캐스팅이 일어날 수 있는 조건**
- 두 배열 간의 연산에서 최소한 하나의 배열의 차원이 1인 경우(0번 축이든 1번 축이든; 1행이든 1열이든)
- 차원의 짝이 맞을 때(차원에 대해 축의 길이가 동일하면)

##  통계를 위한 연산

- 배열의 합, 평균, 표준편차, 분산, 최소값, 최대값, 누적합, 누적곱 등
- https://numpy.org/doc/stable/reference/routines.statistics.html

In [18]:
arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [19]:
# 합과 (산술)평균 : sum(), mean()
[arr1.sum(), arr1.mean()]

[10, 2.0]

In [20]:
# 표준편차와 분산 : std(), var()
[arr1.std(), arr1.var()]

[1.4142135623730951, 2.0]

In [21]:
# 최소값과 최대값 : min(), max()
[arr1.min(), arr1.max()]

[0, 4]

In [22]:
# 누적합과 누적곱
arr2 = np.arange(1,5)
arr2

array([1, 2, 3, 4])

In [25]:
# 누적합
arr2.cumsum()

array([ 1,  3,  6, 10], dtype=int32)

In [26]:
# 누적곱 : cumprod()
arr2.cumprod()

array([ 1,  2,  6, 24], dtype=int32)

## 행렬 연산

- 선형 대수(Linear algebra)를 위한 행렬(2차원 배열) 연산
- 행렬 곱, 전치 행렬, 역행렬, 행렬식 등

    - 행렬곱(matrix product)  : A.dot(B) 혹은 np.dot(A,B)
    - 전치행렬(transpose matrix) : A.transpose() 혹은 np.transpose(A)
    - 역행렬(inverse matrix) : np.linalg.inv(A)
    - 행렬식(determinant) : np.linalg.det(A)

In [27]:
A = np.arange(1,5).reshape(2,2)
# A = np.array([[1,2][3,4]])
# A = np.array([1,2,3,4]).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [ ]:
B = np.