In [2]:
import numpy as np

In [6]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

**2차원배열명[행위치]**

: 2차원 배열에서 지정한 행 전체가 선택됨

In [47]:
# 두번째 행(1행) 선택
arr2[1]

array([-5,  1, 10,  9])

**2차원배열명[:,열위치]**

: 2차원 배열에서 지정한 열 전체 선택

In [42]:
arr2[:,1]

array([ 2,  1, 10])

**2차원 배열의 특정 행을 지정해서 행 전체를 변경**

In [16]:
# 두번째 행 변경
arr2[1]=np.array([-5,1,10,9])

In [17]:
# 변경된 배열 확인
arr2

array([[ 1,  2,  3,  4],
       [-5,  1, 10,  9],
       [ 9, 10, 11, 12]])

**배열명[[행위치1, 행위치2, ..., 행위치n],[열위치1, 열위치2,...,열위치n]]**

: 지정한 (행위치1, 열위치1), (행위치2, 열위치2), ... ,(행위치n, 열위치n)의 원소를 가져옴 

In [19]:
arr2[[0,2],[0,1]]

array([ 1, 10])

### 배열명[조건]

: 배열에서 조건을 만족하는 원소만 선택

In [20]:
# -10 이상인 원소 선택

In [21]:
arr2 > 10

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True]])

In [22]:
# 비교연산 결과를 인덱스로 지정
arr2[arr2>10]

array([11, 12])

In [24]:
# 짝수인 원소 선택
arr2[arr2 % 2 == 0]

array([ 2,  4, 10, 10, 12])

### 1차원 배열의 슬라이싱(Slicing)

**배열[시작위치:끝위치]**

: 시작위치에서 끝위치-1 에 해당하는 배열의 원소를 반환

In [26]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
# 3번째 요소부터 8번째 요소
arr1[3:9]

array([3, 4, 5, 6, 7, 8])

**배열[start:end+1:step]**

  : start에서 end 범위까지의 자료 중 step 간격의 인덱스를 지정

In [31]:
arr1[3:9:2]
# arr1[[3,5,7]]

array([3, 5, 7])

In [32]:
arr1[:9:2]

array([0, 2, 4, 6, 8])

In [35]:
arr1[3::2]

array([3, 5, 7, 9])

In [36]:
arr1[::3]

array([0, 3, 6, 9])

In [37]:
arr1[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [38]:
arr1[::-2]

array([9, 7, 5, 3, 1])

**배열[:끝위치]**

: 처음부터 '끝위치-1' 원소 반환

In [39]:
arr1[:3]

array([0, 1, 2])

**배열[시작위치:]**

: 시작위치부터 마지막 원소까지 반환

In [40]:
arr1[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

**배열[:]**

: 모든 원소 반환

In [48]:
arr1[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### 2차원 배열의 슬라이싱

**배열[행시작위치:행끝위치, 열시작위치:열끝위치]**

In [49]:
arr2

array([[ 1,  2,  3,  4],
       [-5,  1, 10,  9],
       [ 9, 10, 11, 12]])

In [54]:
# 2행의 모든 요소 꺼내기
arr2[2,:]

array([ 9, 10, 11, 12])

In [55]:
arr2[2]

array([ 9, 10, 11, 12])

In [56]:
# 3열의 모든 요소 꺼내기
arr2[:,3]

array([ 4,  9, 12])

In [58]:
# 1~2행, 1~2열의 요소
arr2[1:3, 1:3]

array([[ 1, 10],
       [10, 11]])