In [2]:
import numpy as np

## 행렬 연산

- 선형 대수(Linear algebra)를 위한 행렬(2차원 배열) 연산
- 행렬 곱, 전치 행렬, 역행렬, 행렬식 등

    - 행렬곱(matrix product)  : A.dot(B) 혹은 np.dot(A,B)
    - 전치행렬(transpose matrix) : A.transpose() 혹은 np.transpose(A)
    - 역행렬(inverse matrix) : np.linalg.inv(A)
    - 행렬식(determinant) : np.linalg.det(A)

In [4]:
A = np.arange(1,5).reshape(2,2)
# A = np.array([[1,2],[3,4]])
# A = np.array([1,2,3,4]).reshape(2,2)
A

array([[1, 2],
       [3, 4]])

In [6]:
B = np.array([3,2,0,1]).reshape(2,2)
B

array([[3, 2],
       [0, 1]])

**행렬의 곱**

In [7]:
#행렬의 곱
A.dot(B)

array([[ 3,  4],
       [ 9, 10]])

In [8]:
np.dot(A,B)

array([[ 3,  4],
       [ 9, 10]])

**전치행렬**

In [11]:
A.transpose()

array([[1, 3],
       [2, 4]])

In [12]:
np.transpose(A)

array([[1, 3],
       [2, 4]])

**역행렬**

In [13]:
#역행렬(inverse)
np.linalg.inv(A)

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
# 행렬식(determinanat)
np.linalg.det(A)

-2.0000000000000004

In [15]:
# A * inv(A) = l (단위행렬)
np.dot(A,np.linalg.inv(A))

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

## Array 인덱싱(indexing)과 슬라이싱(Slicing)

- 인덱싱(indexing) : 배열의 위치나 조건을 지정해 배열의 원소를 선택하는 것
- 슬라이싱(slicing) : 범위를 지정해 배열의 원소를 선택하는 것
    - : 연산자를 주로 사용

### 1차원 배열의 인덱싱

**배열명[위치]**


- 파이썬의 인덱싱과 동일
- 0번째로 시작함

In [17]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# 0번째 요소
arr1[0]

0

In [19]:
# 3번째 요소
arr1[3]

3

**배열명[[위치1, 위치2, ... ,위치n]]** 

In [20]:
# 1, 3, 4, 위치 : 
# shape : (m, ) => 1차원, (m, n) => 2차원,  (m, n, p) => 3차원
# 인덱스 [ ]  : [m] => 1차원,  [m,n] => 2차원,  [m,n,p] => 3차원
# arr1[[1,3,4] => 3차원 배열의 위치 1면 3행 4열
# 여러 인덱스의 요소들을 지정 : 리스트로 주어야 한다
arr1[[1,3,4]]

array([1, 3, 4])

### 2차원 배열의 인덱싱
**배열명[행위치, 열위치]**

In [23]:
arr2 = np.arange(1,13).reshape(3,4)
arr2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
# 2차원의 array에서 인덱싱을 하기 위해선 2개의 인자를 입력해야 합니다.
arr2[2,3]  # 2행3열의 요소

12

In [33]:
#0행0열의 값 변경
arr2[0,0]=90

In [34]:
# 변경된 array
arr2

array([[90,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])